# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iY2Q5j7orZ3VTQnO3R0BNk1ut8TzDWRP
"""

#include <stdio.h>

int main() {
    int n = 5, fact = 1;

    for(int i = 1; i <= n; i++) {
        fact = fact * i;
    }

    printf("Factorial of %d = %d\n", n, fact);

    return 0;
}